name: nombu_beauty
description: "A new Flutter project for NOMBU Beauty services."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.8
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Logonombu.jpg
    - assets/IMG-20260915-WA0037.jpg
