name: nombu_beauty
description: NOMBU Beauty Booking App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Fonts
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

  # Assets
  assets:
    - assets/Logonombu.jpg
